// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=tests/mocks/manager_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	service "ratelimiter/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIManager is a mock of IManager interface.
type MockIManager struct {
	ctrl     *gomock.Controller
	recorder *MockIManagerMockRecorder
	isgomock struct{}
}

// MockIManagerMockRecorder is the mock recorder for MockIManager.
type MockIManagerMockRecorder struct {
	mock *MockIManager
}

// NewMockIManager creates a new mock instance.
func NewMockIManager(ctrl *gomock.Controller) *MockIManager {
	mock := &MockIManager{ctrl: ctrl}
	mock.recorder = &MockIManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIManager) EXPECT() *MockIManagerMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockIManager) Allow(groupName, clientId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", groupName, clientId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockIManagerMockRecorder) Allow(groupName, clientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockIManager)(nil).Allow), groupName, clientId)
}

// GetLimiter mocks base method.
func (m *MockIManager) GetLimiter(groupName, clientId string) (*service.Limiter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimiter", groupName, clientId)
	ret0, _ := ret[0].(*service.Limiter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimiter indicates an expected call of GetLimiter.
func (mr *MockIManagerMockRecorder) GetLimiter(groupName, clientId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimiter", reflect.TypeOf((*MockIManager)(nil).GetLimiter), groupName, clientId)
}
